"""initial schema

Revision ID: 7795405d1976
Revises: 
Create Date: 2026-09-12 12:35:22.723896
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '7795405d1976'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cash_balance', sa.Numeric(), nullable=True),
    sa.Column('buying_power', sa.Numeric(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_snapshots')),
    sa.UniqueConstraint('account_id', 'event_time', 'source', name=op.f('uq_account_snapshots_account_id_event_time_source'))
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('period_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_runs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_backtest_runs_idempotency_key'))
    )
    op.create_table('instruments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('exchange', 'symbol', name=op.f('uq_instruments_exchange_symbol'))
    )
    op.create_table('model_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('strategy_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_model_runs_idempotency_key'))
    )
    op.create_table('news_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('related_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_events')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_news_events_source_external_id'))
    )
    op.create_table('strategy_registry',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('spec_created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('synced_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_registry')),
    sa.UniqueConstraint('strategy_id', 'version', name=op.f('uq_strategy_registry_strategy_id_version'))
    )
    op.create_table('system_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dedup_key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events')),
    sa.UniqueConstraint('dedup_key', name=op.f('uq_system_events_dedup_key'))
    )
    op.create_index('ix_system_events_lookup', 'system_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('broker_orders',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=False),
    sa.Column('client_order_id', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('order_type', sa.String(length=16), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('limit_price', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_broker_orders_instrument_id_instruments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_orders')),
    sa.UniqueConstraint('broker_order_id', 'source', name=op.f('uq_broker_orders_broker_order_id_source'))
    )
    op.create_table('disclosure_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('event_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('filing_type', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_disclosure_events_instrument_id_instruments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disclosure_events')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_disclosure_events_source_external_id'))
    )
    op.create_table('market_bars',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('open_price', sa.Numeric(), nullable=False),
    sa.Column('high_price', sa.Numeric(), nullable=False),
    sa.Column('low_price', sa.Numeric(), nullable=False),
    sa.Column('close_price', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_market_bars_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_bars')),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'event_time', 'source', name=op.f('uq_market_bars_instrument_id_timeframe_event_time_source'))
    )
    op.create_index('ix_market_bars_lookup', 'market_bars', ['instrument_id', 'timeframe', 'event_time'], unique=False)
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('asks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_orderbook_snapshots_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orderbook_snapshots')),
    sa.UniqueConstraint('instrument_id', 'event_time', 'source', name=op.f('uq_orderbook_snapshots_instrument_id_event_time_source'))
    )
    op.create_index('ix_orderbook_snapshots_lookup', 'orderbook_snapshots', ['instrument_id', 'event_time'], unique=False)
    op.create_table('paper_orders',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('client_order_id', sa.String(length=128), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('limit_price', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_paper_orders_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_orders')),
    sa.UniqueConstraint('client_order_id', name=op.f('uq_paper_orders_client_order_id'))
    )
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('avg_price', sa.Numeric(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_positions_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('account_id', 'instrument_id', 'event_time', 'source', name=op.f('uq_positions_account_id_instrument_id_event_time_source'))
    )
    op.create_index('ix_positions_lookup', 'positions', ['account_id', 'instrument_id', 'event_time'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('model_run_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('signal_value', sa.Numeric(), nullable=True),
    sa.Column('signal_label', sa.String(length=32), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_signals_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], name=op.f('fk_signals_model_run_id_model_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals')),
    sa.UniqueConstraint('model_run_id', 'instrument_id', 'event_time', name=op.f('uq_signals_model_run_id_instrument_id_event_time'))
    )
    op.create_table('trade_ticks',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_trade_ticks_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_ticks')),
    sa.UniqueConstraint('instrument_id', 'event_time', 'source', 'price', 'volume', name=op.f('uq_trade_ticks_instrument_id_event_time_source_price_volume'))
    )
    op.create_index('ix_trade_ticks_lookup', 'trade_ticks', ['instrument_id', 'event_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_ticks_lookup', table_name='trade_ticks')
    op.drop_table('trade_ticks')
    op.drop_table('signals')
    op.drop_index('ix_positions_lookup', table_name='positions')
    op.drop_table('positions')
    op.drop_table('paper_orders')
    op.drop_index('ix_orderbook_snapshots_lookup', table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    op.drop_index('ix_market_bars_lookup', table_name='market_bars')
    op.drop_table('market_bars')
    op.drop_table('disclosure_events')
    op.drop_table('broker_orders')
    op.drop_index('ix_system_events_lookup', table_name='system_events')
    op.drop_table('system_events')
    op.drop_table('strategy_registry')
    op.drop_table('news_events')
    op.drop_table('model_runs')
    op.drop_table('instruments')
    op.drop_table('backtest_runs')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
