"""revision history for correctable events

Revision ID: c74c2b4cd262
Revises: 7795405d1976
Create Date: 2026-09-12 13:14:17.029874
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'c74c2b4cd262'
down_revision: str | None = '7795405d1976'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disclosure_events', sa.Column('revision', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_disclosure_events_source_external_id'), 'disclosure_events', type_='unique')
    op.create_unique_constraint(op.f('uq_disclosure_events_source_external_id_available_at'), 'disclosure_events', ['source', 'external_id', 'available_at'])
    op.add_column('market_bars', sa.Column('revision', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_market_bars_instrument_id_timeframe_event_time_source'), 'market_bars', type_='unique')
    op.create_unique_constraint(op.f('uq_market_bars_instrument_id_timeframe_event_time_source_available_at'), 'market_bars', ['instrument_id', 'timeframe', 'event_time', 'source', 'available_at'])
    op.add_column('news_events', sa.Column('revision', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_news_events_source_external_id'), 'news_events', type_='unique')
    op.create_unique_constraint(op.f('uq_news_events_source_external_id_available_at'), 'news_events', ['source', 'external_id', 'available_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_news_events_source_external_id_available_at'), 'news_events', type_='unique')
    op.create_unique_constraint(op.f('uq_news_events_source_external_id'), 'news_events', ['source', 'external_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('news_events', 'revision')
    op.drop_constraint(op.f('uq_market_bars_instrument_id_timeframe_event_time_source_available_at'), 'market_bars', type_='unique')
    op.create_unique_constraint(op.f('uq_market_bars_instrument_id_timeframe_event_time_source'), 'market_bars', ['instrument_id', 'timeframe', 'event_time', 'source'], postgresql_nulls_not_distinct=False)
    op.drop_column('market_bars', 'revision')
    op.drop_constraint(op.f('uq_disclosure_events_source_external_id_available_at'), 'disclosure_events', type_='unique')
    op.create_unique_constraint(op.f('uq_disclosure_events_source_external_id'), 'disclosure_events', ['source', 'external_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('disclosure_events', 'revision')
    # ### end Alembic commands ###
