"""ai context annotations

Revision ID: b1bd90a09a95
Revises: c74c2b4cd262
Create Date: 2026-09-13 12:54:38.908181
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'b1bd90a09a95'
down_revision: str | None = 'c74c2b4cd262'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_context_annotations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('event_kind', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('impact_direction', sa.String(length=16), nullable=False),
    sa.Column('impact_duration', sa.String(length=16), nullable=False),
    sa.Column('novelty', sa.String(length=16), nullable=False),
    sa.Column('duplicate_cluster_id', sa.String(length=128), nullable=True),
    sa.Column('source_reliability', sa.String(length=16), nullable=False),
    sa.Column('impact_horizon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_context_annotations')),
    sa.UniqueConstraint('source', 'external_id', 'event_kind', 'model_name', 'model_version', name=op.f('uq_ai_context_annotations_source_external_id_event_kind_model_name_model_version'))
    )
    op.create_index('ix_ai_context_annotations_lookup', 'ai_context_annotations', ['source', 'external_id', 'event_kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_context_annotations_lookup', table_name='ai_context_annotations')
    op.drop_table('ai_context_annotations')
    # ### end Alembic commands ###
